"""orders table init

Revision ID: 37205b26dbb9
Revises: 
Create Date: 2026-01-04 02:50:51.730650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37205b26dbb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    # op.drop_index('ix_public_refreshtoken_token', table_name='refreshtoken')
    # op.drop_index('ix_public_refreshtoken_user_id', table_name='refreshtoken')
    # op.drop_table('refreshtoken')
    # op.drop_table('user')
    # op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('alembic_version',
#     sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
#     sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
#     )
#     op.create_table('user',
#     sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.PrimaryKeyConstraint('id', name='user_pkey'),
#     postgresql_ignore_search_path=False
#     )
#     op.create_table('refreshtoken',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
#     sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
#     sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='refreshtoken_user_id_fkey'),
#     sa.PrimaryKeyConstraint('id', name='refreshtoken_pkey')
#     )
#     op.create_index('ix_public_refreshtoken_user_id', 'refreshtoken', ['user_id'], unique=False)
#     op.create_index('ix_public_refreshtoken_token', 'refreshtoken', ['token'], unique=True)
#     op.drop_table('order', schema='orders')
#     # ### end Alembic commands ###
