"""update order models

Revision ID: ac45e60c6efb
Revises: 37205b26dbb9
Create Date: 2026-01-08 00:30:57.976282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac45e60c6efb'
down_revision: Union[str, None] = '37205b26dbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.String(length=50), server_default='pending', nullable=False), schema='orders')
    op.add_column('order', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='orders')
    op.add_column('order', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'updated_at', schema='orders')
    op.drop_column('order', 'created_at', schema='orders')
    op.drop_column('order', 'status', schema='orders')
    # ### end Alembic commands ###
